### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by meher421** [materialos/Icons#106]
Hi,
    looking to change and add a refreshed/glossy/Material icon for my application APK Extractor.
Request to provide one.
[https://play.google.com/store/apps/details?id=com.ext.ui&hl=en](url)

**Comment by crutchcorn** [comment]
Daniel has already provided you with many great options.

**Comment by meher421** [comment]
Yeah..
https://github.com/materialos/Icons/issues/85

Thanks to Daniel.Its a change request , i could not follow up on the previous issue.
But its almost an year  and looking for a new icon.

Thanks
Meher
