### ISSUE TITLE
Move to LFS

### ISSUE THREAD

**Issue by crutchcorn** [materialos/Icons#109]
Weirdly, binary files aren't best suited by standard git. Let's go on 'head and move things to LFS

**Comment by danielhickman** [comment]
Can this be done without buying the storage from GitHub *easily*?

**Comment by crutchcorn** [comment]
Every user and organization on GitHub.com with Git LFS enabled will begin with 1 GB of free file storage and a monthly bandwidth quota of 1 GB. 

https://github.com/blog/1986-announcing-git-large-file-storage-lfs

**Comment by danielhickman** [comment]
That suffices but it's 25% full after we add everything in /Files/. And if four people download the entire via using LFS, wouldn't that put use over our bandwidth for the month?

**Comment by crutchcorn** [comment]
Ahh crap. I misunderstood what that said. Another option needs to be researched and found, then.

**Comment by TWellington** [comment]
Why move everything? What's happenin?

**Comment by crutchcorn** [comment]
We're back in business! We restructured so that we can have better organization and be more open as a project.

**Comment by TWellington** [comment]
Okay! Sweet. Keep me in the loop

**Comment by danielhickman** [comment]
We can use an implementation of an LFS server but GitHub's is currently "not in a production ready state".

https://github.com/git-lfs/lfs-test-server
