### ISSUE TITLE
Linux Guidelines Unedited

### ISSUE THREAD

**Issue by danielhickman** [materialos/Icons#11]
I only edited the Linux Guidelines from the Android ones for the `File` header. We need to have the downscaled instructions in there.

**Comment by crutchcorn** [comment]
What do you mean?

**Comment by danielhickman** [comment]
Check the Wiki. It should show the correct metrics for 48x48 instead of 192x192

**Comment by adueppen** [comment]
For most things, you would just have to divide it by 4. I'll edit it and make a pull request.

**Comment by danielhickman** [comment]
Thanks. Will move it to the wiki as well later.

**Comment by danielhickman** [comment]
Move to the wiki as well. Thanks @adueppen
