### ISSUE TITLE
Whole Icon guideline / Drop shadow / what opacity ?

### ISSUE THREAD

**Issue by willowbrae** [materialos/Icons#114]
Opacity of the shadow isn't mentioned. 
Most of the time I see around 24% (and 12% when two shadows are present).

**Comment by crutchcorn** [comment]
@danielhickman I think we decided that we weren't handling while icon shadow? Am I incorrect on that?

**Comment by danielhickman** [comment]
You are correct @willowbrae. 24 and 12 percent for "KMZ Style" and 20 percent for vanilla. Most icons use vanilla and I think it'll stay like that for the foreseeable future. 

@crutchcorn I decided to leave it in. I edited the Guidelines on the wiki and didn't realize the opacities were missing. 

Will close when I get a chance to update the wiki double checking the values.

**Comment by crutchcorn** [comment]
Gotcha. My bad!

**Comment by danielhickman** [comment]
Done. Let me know if anything looks off.
[`wiki/Guidelines#kmz-style`](https://github.com/materialos/Icons/wiki/Guidelines#kmz-style)

**Comment by willowbrae** [comment]
@danielhickman Thanks. What about vanilla?

**Comment by danielhickman** [comment]
The vanilla one is a normal drop shadow but with black color. It's pretty light and doesn't really match any other icon but I can't find a source of another one. I fixed the wiki.
