### ISSUE TITLE
Add Our Enforced Copyrights

### ISSUE THREAD

**Issue by danielhickman** [materialos/Icons#15]
> ~~Copyright `Person's Name, no nicknames allowed`. Permitted for use in the Material Open Source project. Additional licensing is only made available by the authors above.~~

> Copyright Daniel Hickman and Corbin Crutchley. View our license at http://materialos.com/license/ 
Credit: {Designer}.

~~**Authors:**~~
~~- [ ] Anas Khan~~
~~- [x] Brian Medina~~
~~- [x] Corbin Crutchley~~
~~- [ ] Createme~~
~~- [x] Daniel Ciao~~
~~- [x] Daniel Hickman~~
~~- [x] Eduardo Pratti~~
~~- [ ] Gabriel Zegarra (see #7)~~
~~- [x] Greg Ives~~
~~- [x] Jahir Fiquitiva & Corbin Crutchley~~
~~- [x] Jireh Mark Morilla~~
~~- [x] Niko Pennanen~~
~~- [x] Oscar E.~~
~~- [ ] Patryk Goworowski~~
~~- [x] Sky Konig~~
~~- [ ] Vukasin Andelkovic~~
~~- [ ] Wayne Kosimoto~~
~~- [x] Zachary Pierson~~

**Authors:**
- [x] Anas Khan
- [x] Brian Medina
- [x] Corbin Crutchley
- [x] Createme
- [x] Daniel Ciao
- [x] Daniel Hickman
- [x] Eduardo Pratti
- [x] Gabriel Zegarra (see #7)
- [x] Greg Ives
- [x] Jahir Fiquitiva & Corbin Crutchley
- [x] Jireh Mark Morilla
- [x] Niko Pennanen
- [x] Oscar E.
- [x] Patryk Goworowski
- [x] Sky Konig
- [x] Vukasin Andelkovic
- [x] Wayne Kosimoto
- [x] Zachary Pierson

**SVG:**
- [x] Createme
- [x] Wayne Kosimoto
- [x] Zachary Pierson

**Comment by crutchcorn** [comment]
Perfect. :+1: Thanks!

**Comment by crutchcorn** [comment]
We also need @createme 's real name

**Comment by danielhickman** [comment]
@crutchcorn Good catch. Yeah, no one can enforce copyrights with a nickname. :stuck_out_tongue_closed_eyes:

**Comment by danielhickman** [comment]
Done all edit ones for Greg Ives

**Comment by danielhickman** [comment]
Done all edited Gabe's. He still has vectors without copyright notice.

**Comment by danielhickman** [comment]
Finished Sky's. Editing his now.

**Comment by danielhickman** [comment]
We are moving to a new copyright that is easier to enforce.

**Comment by danielhickman** [comment]
Wayne's are done except future edited versions, the one's @crutchcorn edited today, and SVGs (they don't handle XMP, must be done manually for all SVGs)

**Comment by danielhickman** [comment]
Added this to Wayne's SVGs I couldn't open:
```html
<g id="Copyright Daniel Hickman and Corbin Crutchley. View our license at http://materialos.com/license/ Credit: Wayne Kosimoto."></g>
```

**Comment by danielhickman** [comment]
Actually SVGs exported through AI still don't have the XMP data. I feel like we have'd solid evidence regardless and will not reopen this issue.
