### ISSUE TITLE
Icon Wishlist

### ISSUE THREAD

**Issue by crutchcorn** [materialos/Icons#16]
- [x] Terraria
- [x] Minecraft
- [ ] AndroidVNC
- [ ] Play Games
- [ ] GEM Music Player
- [x] Snapchat
- [x] Facebook Lite
- [x] Pushbullet
- [x] Pandora
- [ ] Wifi Tether
- [x] YAATA
- [x] SuperSU
- [ ] City2048
- [ ] Shuttle
- [x] Skype
- [x] Twitter
- [ ] Slack
- [ ] Screencast
- [x] Downloads
- [ ] BaconReader
- [x] Tumblr
- [ ] Pebble Dashboard
- [ ] ConnectBot
- [x] Pandora
- [x] Shazam
- [ ] Tapatalk
- [ ] Voice Search
- [ ] Voice Recording

**Comment by danielhickman** [comment]
![Minecraft](https://raw.githubusercontent.com/materialos/Illustrations/87d168f229ede513680f5002c01b88da9f5dec2c/Daniel%20Hickman/MaterialUp/Raster/Minecraft/color-one-shadow.png)

This was hard to do with all Material colors. Like really hard.

**Comment by danielhickman** [comment]
Thunder stuck when I was working on my Terriria. Bummer. Can't work until a while, I hope my work is there.

**Comment by danielhickman** [comment]
Snapchat, SuperSU, and Pushbullet are done if I'm correct.

**Comment by danielhickman** [comment]
![Terraria](https://raw.githubusercontent.com/materialos/Illustrations/c767259eff4ae30d848ccebcdf517daa1e6297ac/Daniel%20Hickman/MaterialUp/Raster/Terraria/color-one-shadow.png)

**Comment by danielhickman** [comment]
SuperSU: https://github.com/materialos/Icons/blob/master/Daniel%20Hickman/Raster/supersu.png
Snapchat: https://github.com/materialos/Icons/blob/master/Gabriel%20Zegarra%20(Gaigzean)/Vector/Snapchat.ai
Pushbullet: https://github.com/materialos/Icons/blob/master/Greg%20Ives%20(Grives)/Raster/Original/pushbullet.png
Pandora: https://github.com/materialos/Icons/blob/master/Daniel%20Hickman/Raster/pandora.png

**Comment by danielhickman** [comment]
![Facebook Lite](https://raw.githubusercontent.com/materialos/Illustrations/f1c538356615564f2b204d28280210754c891aaf/Gabriel%20Zegarra/MaterialUp/Raster/Facebook%20Lite/color-one-shadow.png)

**Comment by danielhickman** [comment]
Improved Minecraft:
![Minecraft](https://raw.githubusercontent.com/materialos/Icons/6db45870cfefba018f39bb0ec7b5e673eeef4356/Daniel%20Hickman/Raster/minecraft/minecraft.png)

**Comment by crutchcorn** [comment]
I could have committed a Minecraft icon I've done before but decided not to. Sorry to waste your time cuz it looks 1:1 as one I already did lmao

**Comment by danielhickman** [comment]
You went through the same pain as I did making it Material colors?!?

**Comment by crutchcorn** [comment]
Yes. Lmao. Sorry mate

**Comment by crutchcorn** [comment]
Added a ton more

**Comment by danielhickman** [comment]
**Previously Done:**
(I checked them off because they can already be found on this repo, please ask if they should be edited or rethemed)
* Skype
* Twitter
* Pandora
* Tumblr
* Shazam

**Done:**
(Recently completed, checked off)
* Downloads

**More Information:**
(Not sure what these are)
* Screencast
* Pebble Dashboard
* Voice Search
* Voice Recording

**Has Material by Default:**
(These already have Material Icons, please specify if they should also be themed not checked off)
* Play Games
* GEM Music Player

**Comment by crutchcorn** [comment]
I kinda want new icons for Play Games, though GEM has way too many icons as it is.
Pebble Dashboard (I would like to do this):
https://play.google.com/store/apps/details?id=com.wordpress.ninedof.dashboard&hl=en
I will send you an icon request via the app for the other 3 icons

**Comment by crutchcorn** [comment]
Closing this, as Android icon requests belong in #56 and need their respective codes following the name request
