### ISSUE TITLE
Add Icon Licence for Devs

### ISSUE THREAD

**Issue by danielhickman** [materialos/Icons#3]
Add more open licence for developers of the original apps to allow the Material Design standard to spread.

**Comment by crutchcorn** [comment]
I say that we make it so that anyone can use it in their app or anywhere at all - just so long as they speak with the designer beforehand (or at lease is given permission). That can go through us possibly if need be

**Comment by danielhickman** [comment]
Should we modify CC SA 4.0 to match that better, or make the copyright
closed, and we release it open request?

**Comment by crutchcorn** [comment]
Modify the CC SA 4.0.

**Comment by danielhickman** [comment]
After reading through this https://wiki.creativecommons.org/wiki/Modifying_the_CC_licenses

I found out that we shouldn't use "Modified Creative Commons" in the license, even though we can further limit or open the existing license. 

I'll be working on this soon. I wish we had someone with a legal background to check it, but that may be over the top for now.

**Comment by crutchcorn** [comment]
That would be really nice to have someone with a legal background. Make a few posts on G+ and I'll help you out too

**Comment by danielhickman** [comment]
**Material Open Source is now CC By 4.0**

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/StillImage" property="dct:title" rel="dct:type">Material Design Iconography</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://github.com/materialos/Icons" property="cc:attributionName" rel="cc:attributionURL">the MOS Contributors</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
