### ISSUE TITLE
Check with Michael Cook For Icons

### ISSUE THREAD

**Issue by danielhickman** [materialos/Icons#4]
He has a few "remakes" and some which would be helpful to our pack.

**Comment by crutchcorn** [comment]
How so? Explain more

**Comment by danielhickman** [comment]
His website has Instagram, YouTube Kiddos, etc. Also he's going to have
extra Relay for Reddit ones.

**Comment by crutchcorn** [comment]
You think he'd be willing to commit? Should I talk to him?

**Comment by danielhickman** [comment]
Together some time.

**Comment by crutchcorn** [comment]
Sounds good

**Comment by crutchcorn** [comment]
Just checked with him. Awaiting for a zip

**Comment by danielhickman** [comment]
Any update?

**Comment by crutchcorn** [comment]
Not yet. Still waiting for him to edit them
