### ISSUE TITLE
[Request] Icons needed for MOS CM12

### ISSUE THREAD

**Issue by Anonymas** [materialos/Icons#54]
- [x] Audiofx
- [x] Calculator
- [x] Camera
- [x] Calendar
- [x] Downloads
- [x] Hangouts
- [x] Phone
- [x] Google Photos (?)
- [x] Google Settings
- [x] Sound Recorder
- [x] UC Browser
- [x] Voice Search

 That's it for now.

**Comment by danielhickman** [comment]
☑ Calculator
☑ Camera
☑ Calendar

**Comment by danielhickman** [comment]
Completed!
