### ISSUE TITLE
Request From Jaden Pleasants

### ISSUE THREAD

**Issue by danielhickman** [materialos/Icons#58]
>There's a chromium alt icon. 
>Here's the stuff for chromium. 
>As you can see, it has no reason to be an alt. 
>Also it's not in the play store. It's in a Google storage bucket. 
>Also there are 2 other apk files that pop up in the storage bucket. This is the only important one.
>
>Name: Chromium
>Code: org.chromium.chrome/com.google.android.apps.chrome.Main
>Link: http://commondatastorage.googleapis.com/chromium-browser-continuous/index.html?prefix=Android/
>
>OS Version: 3.4.0-4445722(N900VVRUEOF1)
>OS API Level: 21
>Device: hltevzw
>Manufacturer: samsung
>Model (and Product): SM-N900V (hltevzw)
>App Version Name: 1.0.0
>App Version Code: 6

I'm not sure what's he's talking about with "Google storage bucket", but the Chrome icons are all wildly different and I was thinking the ones to replace should be consistent among themselves.

**Comment by danielhickman** [comment]
>The icon is already Material, right? My idea is to not theme already Material icons. I also didn't know that Chromium had a public Android app.
> Email in reply.

**Comment by crutchcorn** [comment]
Chromium does indeed have public builds, however - the icon IS Material Design, IIRC.
