### ISSUE TITLE
Pinned Post and Wiki Home Page

### ISSUE THREAD

**Issue by danielhickman** [materialos/Icons#6]
We should make a pinned post on G+ reflecting what a new user should do:
Guidelines, contributing instructions, how to view icons, stress that there is not an APK just yet, icon suggestion, etc

**Comment by crutchcorn** [comment]
Do you want me to type that up?

**Comment by danielhickman** [comment]
> danielhickman self-assigned this just now
> GitHub

**Comment by crutchcorn** [comment]
Nevermind. Lol

**Comment by danielhickman** [comment]
@crutchcorn If you could make something up I guess that would take something off my plate. I'll edit it later. Feel free to change the assignment if you're okay with that.

**Comment by danielhickman** [comment]
Finished. I will continue polishing up the other repos.
