### ISSUE TITLE
Edit Icons

### ISSUE THREAD

**Issue by danielhickman** [materialos/Icons#7]
**Authors:**
- [x] Alex Mueller
- [ ] Anas Khan
- [x] Brian Medina
- [x] Corbin Crutchley
- [ ] Createme
- [x] Daniel Ciao
- [x] Daniel Hickman
- [x] Eduardo Pratti
- [x] Gabriel Zegarra
- [x] Greg Ives
- [x] Jahir Fiquitiva & Corbin Crutchley
- [x] Jireh Mark Morilla
- [x] Niko Pennanen
- [x] Oscar E.
- [x] Patryk Goworowski
- [x] Sky Konig
- [x] Vukasin Andelkovic
- [ ] Wayne Kosimoto
- [x] Zachary Pierson

**Anas':**
- [ ] android
- [ ] androidwear
- [ ] calculator
- [ ] camera
- [ ] chrome
- [ ] chromecast
- [ ] colorcons
- [ ] contacts
- [ ] currents
- [ ] dailer
- [ ] downloads
- [ ] drive
- [ ] facebookmessenger
- [ ] gallery
- [ ] googleauthenticator
- [ ] googleearth
- [ ] googlekeep
- [ ] googlemaps
- [ ] googlephotos
- [ ] googleplay
- [ ] googleplaybooks-alt
- [ ] googleplaybooks
- [ ] googleplaygames
- [ ] googleplaymovies
- [ ] kiosk
- [ ] music
- [ ] settings
- [ ] sms-alt
- [ ] sms
- [ ] translate
- [ ] twitter
- [ ] videoeditor
- [ ] voicesearch
- [ ] whatsapp
- [ ] youtube

**Gabe's:**
- [x] Pocket
- [x] Quickpic
- [x] Retrica
- [x] Runtastic
- [x] Shazam
- [x] Skype
- [x] Snapchat
- [x] Sound Hound
- [x] Soundcloud
- [x] Tinder
- [x] Trello
- [x] Tumblr
- [x] Tune In
- [x] Twitter
- [x] Uber
- [x] Viber
- [x] Vine
- [x] Wattpad
- [x] We Heart It
- [x] Whatsapp
- [x] Wunderlist

**Wayne's:**
- [x] androidstudio
- [x] archivemanager
- [x] barcodescanner
- [x] blankfile
- [x] blender
- [x] chromium
- [x] firefox
- [x] lollypop
- [x] midori
- [ ] moovit
- [x] musicfolder
- [ ] playmusic
- [x] publicfolder
- [x] vlc
- [ ] barcodescanner
- [ ] klwp
- [ ] klwp_alt
- [ ] moovit
- [ ] playmusic-alt
- [ ] playmusic
- [ ] facebook

**Createme's:**
- [x] adaway
- [x] feedly
- [x] gallery
- [x] googleopinionrewards
- [ ] instagram
- [ ] napster
- [ ] netflix
- [ ] pushbullet
- [ ] quickpic
- [ ] rar
- [ ] sim_toolkit
- [ ] snapchat
- [ ] steam
- [x] supersu
- [ ] sync
- [ ] titaniumbackup
- [x] tunein
- [x] unicon
- [x] whatsapp
- [x] wikipedia
- [ ] His recently added icons

**Priority:**
- Wayne Kosimoto - Convert to AI, Double Check
- ~~Gabriel Zegarra - Shadow, Double Check - Assigned to @danielhickman~~
- Anas Khan - Materialize - Assigned to @danielhickman
- ~~Sky Konig - Size, Materialize - Assigned to @danielhickman~~
- ~~Patryk Goworowski - Convert, Shadow, Double Check - Assigned to @danielhickman~~
- Createme - Double Check His are the best and closest though.

~~After first release:~~
- ~~Greg Ives - Convert - Assigned to @danielhickman~~

**Comment by crutchcorn** [comment]
Ensure that @createme icons are consistent with our guidelines as well. Just to check

**Comment by danielhickman** [comment]
Createme's are not sadly. Some of the objects are off my a little. I should edit them as well.

**Comment by crutchcorn** [comment]
Damn. Good to know

**Comment by danielhickman** [comment]
*Edited my icon and Zach's 4*

**Comment by danielhickman** [comment]
I'd like to use Eduardo's style of shading so I'm adding myself back to the editing.
(Two shades, one on and one like a drop shadow)

**Comment by danielhickman** [comment]
Sky's are done!

**Comment by danielhickman** [comment]
To edit Wayne's, delete all selected text from sublime text's regex find all using this:
```javascript
<mask[a-z,0-9,\#,\(,\),\-,\",\:,\=,\s]+>[a-z,0-9,\#,\(,\),\-,\",\:,\=,\s,<,>,/]+</mask>
```

**Comment by danielhickman** [comment]
Converting PSDs to AIs is being moved to #12, Crossed out Patryk and Greg

**Comment by crutchcorn** [comment]
@danielhickman We need to edit this list. This repo has gotten much larger since then

**Comment by createme** [comment]
@danielhickman @crutchcorn editing all my icons to match the guidelines (+ some new ones). what opacy should i use for the icon drop shadow in inkscape?

**Comment by danielhickman** [comment]
I think these metrics
Opacity: 20%
X: 0
Y: 4
Blur: 4
Color: Black

**Comment by createme** [comment]
thanks

**Comment by crutchcorn** [comment]
Closing due to structure change
