### ISSUE TITLE
[Request] Need Apk Extractor App Icon.

### ISSUE THREAD

**Issue by meher421** [materialos/Icons#85]
I have an app in playstore and i need a nice material design icon. Request you to provide a icon, redesign if required.

Thanks
Meher

Name: Apk Extractor
Code: com.ext.ui/com.ext.ui.MainActivity
Link: https://play.google.com/store/apps/details?id=com.ext.ui

**Comment by crutchcorn** [comment]
I'll take care of this request sometime today.

**Comment by meher421** [comment]
ok.. thanks for the update

**Comment by danielhickman** [comment]
**Here's my favorite icon of the ones I made today:**
![apkextractor](https://cloud.githubusercontent.com/assets/5341898/10267033/14ac6642-6a36-11e5-923c-6d2bff07a254.png)

See the whole commit with vector and rasters: https://github.com/materialos/Icons/commit/a9a9dfbad357f3d5b21c66b5a60e6ebc36ec6731

And just a friendly reminder, you should attribute the icon to MaterialOS and link to [this repo](https://github.com/materialos/Icons) inside your app, and if you like, in your Google Play listing.

Let me know if you'd like to see a different style or want something changed.

**Comment by meher421** [comment]
Hi Daniel,
                Thanks for the Icon,it looks good, but when i see these icons in my device (Nexus 4) on a White Background ,compared to other icons in the launcher  , icon looks dim and dull and most importantly this does not look like material icon. Please do not go with my existing app icon, and use some bright color and possible circular with out any text.

**Comment by danielhickman** [comment]
![screenshot_2015-10-04-18-09-48](https://cloud.githubusercontent.com/assets/5341898/10271425/5512953e-6ac3-11e5-93d3-2ad8f6f1308f.png)

The white area is from setting the icon incorrectly, it will look like the above when it's included in the app. 

It is a Material Design icon, I'm afraid. And the "dim and dull" colors cone from the Material Palette. And I don't think it'd be easy to illustrate a package (apk) without text and circular. I might have another crack at it later, but we're all a little busy and I've already spent hours on it.
