### ISSUE TITLE
All SVG Icons are Incorrect

### ISSUE THREAD

**Issue by danielhickman** [materialos/Icons#9]
Inkscape doesn't seem to be able to export the <inkscape-shadow> to where I can edit them, I've seen too many keyline shapes being off center or off by a pixel in height.

I'm voting for AI to be a requirement. These extra file types seem to be adding more to my work where I can't go very far with them. :/

**Comment by loctauxphilippe** [comment]
@crutchcorn was able to export an svg icon from AI without any problems.
People can use whatever to create icons but they must be 48X48 svg icons for the linux set.

**Comment by danielhickman** [comment]
Good. In that case I'll add that to the guidelines. It's just a shame I can't edit the other SVGs that were sent.

**Comment by loctauxphilippe** [comment]
@danielhickman you're welcome! no problem!
