### ISSUE TITLE
MaterialOS - Icon Requests

### ISSUE THREAD

**Issue by M2ck** [materialos/Icons#97]
These apps are not themed.
Thanks in advance!

Name: AlloCiné
Code: com.allocine.androidapp/com.allocine.androidapp.activities.SplashActivity
Link: https://play.google.com/store/apps/details?id=com.allocine.androidapp

Name: AnySoftKeyboard
Code: com.menny.android.anysoftkeyboard/com.menny.android.anysoftkeyboard.LauncherSettingsActivity
Link: https://play.google.com/store/apps/details?id=com.menny.android.anysoftkeyboard

Name: AppHunt
Code: com.livae.apphunt.app/com.livae.apphunt.app.ui.activity.AppHuntActivity
Link: https://play.google.com/store/apps/details?id=com.livae.apphunt.app

Name: Camera
Code: com.oneplus.camera/com.oneplus.camera.OPCameraActivity
System app

Name: Chronus
Code: com.dvtonder.chronus/com.dvtonder.chronus.preference.PreferencesMain
Link: https://play.google.com/store/apps/details?id=com.dvtonder.chronus

Name: Contacts
Code: com.android.contacts/com.android.contacts.activities.PeopleActivity
System app

Name: CPUSpy
Code: org.axdev.cpuspy/org.axdev.cpuspy.activity.MainActivity
Link: http://forum.xda-developers.com/google-nexus-5/themes-apps/app-cpu-spy-material-v1-0-t2948627

Name: Darker
Code: com.mlhg.screenfilter/com.mlhg.screenfilter.MainActivity
Link: https://play.google.com/store/apps/details?id=com.mlhg.screenfilter

Name: Etar
Code: ws.xsoh.etar/com.android.calendar.AllInOneActivity
Link: https://play.google.com/store/apps/details?id=ws.xsoh.etar

Name: Eurosport
Code: com.eurosport/com.eurosport.universel.ui.tablet.SplashscreenActivity
Link: https://play.google.com/store/apps/details?id=com.eurosport

Name: Event Flow Widget
Code: com.syncedsynapse.eventflowwidget/com.syncedsynapse.eventflowwidget.agenda.config.AgendaConfigurationLauncherActivity
Link: https://play.google.com/store/apps/details?id=com.syncedsynapse.eventflowwidget

Name: F-Droid
Code: org.fdroid.fdroid/org.fdroid.fdroid.FDroid
Link: https://f-droid.org/repository/browse/?fdfilter=F-Droid&fdid=org.fdroid.fdroid

Name: Files
Code: com.android.documentsui/com.android.documentsui.DocumentsActivity
System app

Name: Flyperlink
Code: com.flyperinc.flyperlink/com.flyperinc.flyperlink.activity.History
Link: https://play.google.com/store/apps/details?id=com.flyperinc.flyperlink

Name: Google Play Services
Code: com.google.android.gms/com.google.android.gms.app.settings.GoogleSettingsActivity
Link: https://play.google.com/store/apps/details?id=com.google.android.gms

Name: Instant Translate
Code: com.evgvin.instanttranslate/com.evgvin.instanttranslate.MainActivity
Link: https://play.google.com/store/apps/details?id=com.evgvin.instanttranslate

Name: K-9 Mail
Code: com.fsck.k9/com.fsck.k9.activity.Accounts
Link: https://play.google.com/store/apps/details?id=com.fsck.k9

Name: Lightning
Code: acr.browser.barebones/acr.browser.lightning.activity.MainActivity
Link: https://play.google.com/store/apps/details?id=acr.browser.barebones

Name: MAPS.ME
Code: com.mapswithme.maps.pro/com.mapswithme.maps.DownloadResourcesActivity
Link: https://play.google.com/store/apps/details?id=com.mapswithme.maps.pro

Name: MaterialOS
Code: org.materialos.icons/org.materialos.icons.HomeActivity
Link: https://play.google.com/store/apps/details?id=org.materialos.icons

Name: Micopi
Code: com.easytarget.micopi/com.easytarget.micopi.ui.WelcomeActivity
Link: https://play.google.com/store/apps/details?id=com.easytarget.micopi

Name: Minimal Brick Breaker
Code: com.minimal.brick.breaker.android/com.minimal.brick.breaker.android.AndroidLauncher
Link: https://play.google.com/store/apps/details?id=com.minimal.brick.breaker.android

Name: MuPDF
Code: com.artifex.mupdfdemo/com.artifex.mupdfdemo.ChoosePDFActivity
Link: https://play.google.com/store/apps/details?id=com.artifex.mupdfdemo

Name: Native Clipboard
Code: com.dhm47.nativeclipboard/com.dhm47.nativeclipboard.Setting
Link: https://play.google.com/store/apps/details?id=com.dhm47.nativeclipboard

Name: NetGuard
Code: eu.faircode.netguard/eu.faircode.netguard.ActivityMain
Link: https://play.google.com/store/apps/details?id=eu.faircode.netguard

Name: News Republic
Code: com.mobilesrepublic.appy/com.mobilesrepublic.appy.SplashActivity
Link: https://play.google.com/store/apps/details?id=com.mobilesrepublic.appy

Name: Omni Notes
Code: it.feio.android.omninotes/it.feio.android.omninotes.MainActivity
Link: https://play.google.com/store/apps/details?id=it.feio.android.omninotes

Name: OnePlus Radio
Code: com.caf.fmradio/com.caf.fmradio.FMRadio
System app

Name: Papuh
Code: com.alexcruz.papuhwalls/com.alexcruz.papuhwalls.Papuh
Link: https://play.google.com/store/apps/details?id=com.alexcruz.papuhwalls

Name: Piktures
Code: com.diune.pictures/com.diune.pictures.ui.Bridge
Link: https://play.google.com/store/apps/details?id=com.diune.pictures

Name: QKSMS
Code: com.moez.QKSMS/com.moez.QKSMS.ui.MainActivity-Cyan
Link: https://play.google.com/store/apps/details?id=com.moez.QKSMS

Name: Screen Off
Code: nl.matthijsvh.screenoffdonate/nl.matthijsvh.screenoff.ScreenOffActivity
Link: https://play.google.com/store/apps/details?id=nl.matthijsvh.screenoffdonate

Name: Should I Answer?
Code: org.mistergroup.muzutozvednout/org.mistergroup.muzutozvednout.SplashScreenActivity
Link: https://play.google.com/store/apps/details?id=org.mistergroup.muzutozvednout

Name: SIM Toolkit
Code: com.android.stk/com.android.stk.StkLauncherActivity
System app

Name: Solid Explorer
Code: pl.solidexplorer2/pl.solidexplorer.SolidExplorer
Link: https://play.google.com/store/apps/details?id=pl.solidexplorer2

Name: SolitaireCG
Code: net.sourceforge.solitaire_cg/net.sourceforge.solitaire_cg.SolitaireCG
Link: https://play.google.com/store/apps/details?id=net.sourceforge.solitaire_cg

Name: Tachiyomi
Code: eu.kanade.tachiyomi/eu.kanade.tachiyomi.ui.main.MainActivity
Link: https://f-droid.org/repository/browse/?fdfilter=Tachiyomi&fdid=eu.kanade.tachiyomi

Name: Tapatalk
Code: com.quoord.tapatalkpro.activity/com.quoord.tapatalkpro.activity.directory.ics.IcsEntryActivity
Link: https://play.google.com/store/apps/details?id=com.quoord.tapatalkpro.activity

Name: Telecine
Code: com.jakewharton.telecine/com.jakewharton.telecine.TelecineActivity
Link: https://play.google.com/store/apps/details?id=com.jakewharton.telecine

Name: TéléStar
Code: com.mondadori.telestar/com.dotscreen.tele.activities.SplashActivity
Link: https://play.google.com/store/apps/details?id=com.mondadori.telestar

Name: TeslaUnread
Code: com.teslacoilsw.notifier/com.teslacoilsw.notifier.NotifierSettings
Link: https://play.google.com/store/apps/details?id=com.teslacoilsw.notifier

Name: Timely
Code: ch.bitspin.timely/ch.bitspin.timely.activity.MainActivity_
Link: https://play.google.com/store/apps/details?id=ch.bitspin.timely

Name: Torchie
Code: in.blogspot.anselmbros.torchie/in.blogspot.anselmbros.torchie.ui.activity.MainActivity
Link: https://play.google.com/store/apps/details?id=in.blogspot.anselmbros.torchie

Name: Transistor
Code: org.y20k.transistor/org.y20k.transistor.MainActivity
Link: https://play.google.com/store/apps/details?id=org.y20k.transistor

Name: VLC
Code: org.videolan.vlc/org.videolan.vlc.gui.MainActivity
Link: https://play.google.com/store/apps/details?id=org.videolan.vlc

Name: YouTube Downloader
Code: dentex.youtube.downloader/dentex.youtube.downloader.MainActivity
Link: http://forum.xda-developers.com/showthread.php?t=2137743

OS Version: 3.4.0-perf+(2)
OS API Level: 22
Device: OnePlus
Manufacturer: OnePlus
Model (and Product): ONE E1003 (OnePlus)
App Version Name: 1.0.1
App Version Code: 7

**Comment by crutchcorn** [comment]
Moved to #56
