### ISSUE TITLE
Dialer and VLC icons stay unthemed

### ISSUE THREAD

**Issue by M2ck** [materialos/Icons#99]
Noticed on my both devices: OnePlus X - Nova Prime & Samsung Galaxy S2 - CM Theme engine.

**Comment by TWellington** [comment]
Is this still an issue with the most recent update?

**Comment by danielhickman** [comment]
Fixed in dev. VLC changed their activity coming out of beta or something. Reopen if dialer isn't themed as of 2.1 or you have another activity than `org.videolan.vlc/.StartActivity`.
